### ISSUE TITLE
Builds with version 2.0.1 are broken

### ISSUE THREAD

**Issue by morleyzhi** [singular-labs/react-native-sdk#29]
See also https://github.com/singular-labs/segment-singular-android/issues/6

Because Maven is only returning v12.0.0, it's broken builds using v2.0.1. We could upgrade, but we'd have to test it again, and it seems bad for new versions to break previous ones too.

**Comment by morleyzhi** [comment]
It looks like using the new version doesn't work either because it still requires 11.0.0.

**Comment by Mahimsharma** [comment]
@morleyzhi you can patch singular-react-native build.gradle dependencies from     
implementation 'com.singular.sdk:singular_sdk:11.+'  =>  implementation 'com.singular.sdk:singular_sdk:11.0.0' or the exact version that is being used by your app.

Worked for me!🥂


> See also [singular-labs/segment-singular-android#6](https://github.com/singular-labs/segment-singular-android/issues/6)
> 
> Because Maven is only returning v12.0.0, it's broken builds using v2.0.1. We could upgrade, but we'd have to test it again, and it seems bad for new versions to break previous ones too.

**Comment by jayfunk** [comment]
Seeing the same thing and manually changing the singular_sdk version to `11.0.0` resolved the issue for my local build env.

**Comment by jayfunk** [comment]
Yeah if you hit the maven metadata file you can see that only v12 is listed: http://maven.singular.net/com/singular/sdk/singular_sdk/maven-metadata.xml

**Comment by omribaraksingular** [comment]
hi @morleyzhi , 

We are sorry for the inconvenience. 
The issue is resolved on our end and you do not need to manually change anything in order to compile. 

I do suggest you update to the latest version of our react SDK as we add some important[ Android 12 improvements](https://support.singular.net/hc/en-us/articles/360040645272-React-Native-SDK-Change-Log). 

Best, 
Omri Barak 
Product Manager 
Singular
